/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartnerDashboardRouteImport } from './routes/partner-dashboard'
import { Route as GapAnalysisRouteImport } from './routes/gap-analysis'
import { Route as CustomerReportsRouteImport } from './routes/customer-reports'
import { Route as CurManagerRouteImport } from './routes/cur-manager'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'

const PartnerDashboardRoute = PartnerDashboardRouteImport.update({
  id: '/partner-dashboard',
  path: '/partner-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GapAnalysisRoute = GapAnalysisRouteImport.update({
  id: '/gap-analysis',
  path: '/gap-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerReportsRoute = CustomerReportsRouteImport.update({
  id: '/customer-reports',
  path: '/customer-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const CurManagerRoute = CurManagerRouteImport.update({
  id: '/cur-manager',
  path: '/cur-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/cur-manager': typeof CurManagerRoute
  '/customer-reports': typeof CustomerReportsRoute
  '/gap-analysis': typeof GapAnalysisRoute
  '/partner-dashboard': typeof PartnerDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/cur-manager': typeof CurManagerRoute
  '/customer-reports': typeof CustomerReportsRoute
  '/gap-analysis': typeof GapAnalysisRoute
  '/partner-dashboard': typeof PartnerDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/cur-manager': typeof CurManagerRoute
  '/customer-reports': typeof CustomerReportsRoute
  '/gap-analysis': typeof GapAnalysisRoute
  '/partner-dashboard': typeof PartnerDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/cur-manager'
    | '/customer-reports'
    | '/gap-analysis'
    | '/partner-dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/cur-manager'
    | '/customer-reports'
    | '/gap-analysis'
    | '/partner-dashboard'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/cur-manager'
    | '/customer-reports'
    | '/gap-analysis'
    | '/partner-dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CurManagerRoute: typeof CurManagerRoute
  CustomerReportsRoute: typeof CustomerReportsRoute
  GapAnalysisRoute: typeof GapAnalysisRoute
  PartnerDashboardRoute: typeof PartnerDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/partner-dashboard': {
      id: '/partner-dashboard'
      path: '/partner-dashboard'
      fullPath: '/partner-dashboard'
      preLoaderRoute: typeof PartnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gap-analysis': {
      id: '/gap-analysis'
      path: '/gap-analysis'
      fullPath: '/gap-analysis'
      preLoaderRoute: typeof GapAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-reports': {
      id: '/customer-reports'
      path: '/customer-reports'
      fullPath: '/customer-reports'
      preLoaderRoute: typeof CustomerReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cur-manager': {
      id: '/cur-manager'
      path: '/cur-manager'
      fullPath: '/cur-manager'
      preLoaderRoute: typeof CurManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CurManagerRoute: CurManagerRoute,
  CustomerReportsRoute: CustomerReportsRoute,
  GapAnalysisRoute: GapAnalysisRoute,
  PartnerDashboardRoute: PartnerDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
